# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t reverseproxy ./reverseproxy

# Tagging
- docker tag udagram-api-feed docker4mathenge/udagram-api-feed:v1
- docker tag udagram-api-user docker4mathenge/udagram-api-user:v1
- docker tag udagram-frontend docker4mathenge/udagram-frontend:v1
- docker tag reverseproxy docker4mathenge/reverseproxy:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push docker4mathenge/udagram-api-feed:v1
- docker push docker4mathenge/udagram-api-user:v1
- docker push docker4mathenge/udagram-frontend:v1
- docker push docker4mathenge/reverseproxy:v1